"""Reference implementations and golden fixtures for the browser-shader lane.

This package exists to keep the *one* place where the canonical forward math
for Granite-tiny lives: a single PyTorch implementation that is bit-identical
to the HF ``GraniteMoeHybridDecoderLayer`` and is the ground truth that the
WebGPU shaders in ``hivemind-client/static/shaders/granite/`` are validated
against.

Files
-----

- ``granite_layer5.py`` -- pure-PyTorch forward for Granite-tiny layer 5
  (the first attention layer; layers 0-4 are Mamba and out of scope for
  the browser-as-peer Phase 1 demo).
- ``golden/layer5.json`` -- precomputed hidden state + router top-6 for a
  fixed input. Generated by running ``granite_layer5.forward_layer5``
  once on a fixed seed and shape.
- ``golden/router_top6.json`` -- router-only fixture (subset of
  ``layer5.json``) for tests that only care about the MoE router.

Conventions
-----------

- All tensors travel in fp32 on CPU.
- The reference loads Granite-tiny weights from a path passed in by the
  caller. There is no baked-in path: tests use
  ``output/granite-tiny-q4g64/``; production callers may fetch the layer
  shard from the byte server.
- Output is a dict with the keys documented in
  ``conductor/tracks/browser-as-peer-phase1_20260606/handoff-from-claude.md``
  (the contract the TypeScript orchestrator imports).
"""

from __future__ import annotations

__all__: list[str] = []
